ALTER TABLE EMPLOYEE DROP constraint fk_dep_emp;
ALTER TABLE EMPLOYEE DROP constraint fk_fac_emp;
ALTER TABLE DEPARTMENT DROP constraint fk_dm_dep;
ALTER TABLE FACILITY DROP constraint fk_fm_fac;
ALTER TABLE STORES DROP constraint fk_fac_sto;

DROP TABLE STORES;
DROP TABLE FACILITY;
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;